-- Core storage for AI-Powered Student Helpdesk Bot

create table if not exists student_conversations (
  id bigint generated by default as identity primary key,
  session_id text not null,
  source text not null default 'kommunicate',
  intent_name text,
  user_message text,
  bot_response text,
  course_code text,
  confidence numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists student_queries (
  id bigint generated by default as identity primary key,
  student_name text not null,
  student_email text not null,
  course_code text not null,
  query_text text not null,
  source text not null default 'kommunicate',
  status text not null default 'open',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table student_conversations enable row level security;
alter table student_queries enable row level security;

create policy if not exists "allow insert conversations"
on student_conversations for insert
with check (true);

create policy if not exists "allow select conversations"
on student_conversations for select
using (true);

create policy if not exists "allow insert queries"
on student_queries for insert
with check (true);

create policy if not exists "allow select queries"
on student_queries for select
using (true);
